#ARDUINO_DIR            = /usr/share/arduino
#TARGET                 = arkeyboard
#ARDUINO_LIBS           = 
#MCU                    = atmega328p
##F_CPU                  = 16000000
ARDUINO_PORT           = /dev/ttyACM0
#AVRDUDE_ARD_BAUDRATE   = 115200
#AVRDUDE_ARD_PROGRAMMER = arduino
# 
# include /usr/share/arduino/Arduino.mk

ARDMK_DIR = /usr/share/arduino
BOARD_TAG = uno
include $(ARDMK_DIR)/Arduino.mk
